/**
 * The basic idea is to put all action types into a single object to be sure all name strings are the same across the
 * application and do not interfere.
 *
 * @summary Prevents stupid errors. Makes code look neat.
 */

// Auth actions.
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const AUTH = {
  LOGIN_USER_REQUEST,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAIL,
  LOGOUT,
  REFRESH_TOKEN
};

// Candidate actions.
export const GET_CANDIDATE = 'GET_CANDIDATES';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATES';
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';

export const CANDIDATE = {
  GET_CANDIDATE,
  DELETE_CANDIDATE,
  ADD_CANDIDATE,
  UPDATE_CANDIDATE
};

// UserContext actions.
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const USER = {
  GET_USERS_REQUEST,
  GET_USERS_SUCCESS,
  GET_USERS_FAILED,
  GET_USER,
  UPDATE_USER
};


const GET_ACCOUNT_ROLES_REQUEST = 'GET_ACCOUNT_ROLES_REQUEST';
const GET_ACCOUNT_ROLES_SUCCESS = 'GET_ACCOUNT_ROLES_SUCCESS';
const GET_ACCOUNT_ROLES_FAIL = 'GET_ACCOUNT_ROLES_FAIL';

const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';

const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL';

export const ACCOUNT = {
  GET_ACCOUNT_ROLES_REQUEST,
  GET_ACCOUNT_ROLES_SUCCESS,
  GET_ACCOUNT_ROLES_FAIL,

  CREATE_ACCOUNT_REQUEST,
  CREATE_ACCOUNT_SUCCESS,
  CREATE_ACCOUNT_FAIL,

  GET_ACCOUNTS_REQUEST,
  GET_ACCOUNTS_SUCCESS,
  GET_ACCOUNTS_FAIL
};





